### ISSUE TITLE
Memory leak by revuest

### ISSUE THREAD

**Issue by marjakapyaho** [guithess/revuest#2]
Our single-page Vue app had a clear memory leak (none of the reserved memory by the app was ever released during usage) that was fixed by simply removing revuest. I have not produced a more simple scenario to produce this error so if might of course be a joint problem with something else in our app.

In short our app had:
- Vuejs 2.4.2
- vuex 2.2.1
- Server-side rendering

**Comment by guithess** [comment]
Hello @marjakapyaho, sorry for the late reply.

I could not reproduce the memory leak on the tests I made, however I fixed an issue that could potentially lead to a memory leak.

The issue was the event listener for the storage event that was not being removed when the vue instance is destroyed.

Please try version 1.1.4 and see if the issue was indeed resolved and let me know.

Regards!
